import type { CountryRow } from "@/features/countries/types";
import type { FaqRow } from "@/features/faqs/types";
import type { BenefitRow } from "@/features/benefits/types";
import type { SectionTextRow } from "./types";
import { SOCIAL_LINKS } from "@/features/countries/data";

const NOW = "2026-06-20T00:00:00.000Z";

function country(
  partial: Omit<CountryRow, "created_at" | "updated_at" | "addresses" | "subtitle" | "show_subtitle" | "whatsapp_label" | "whatsapp_icon" | "website_label" | "website_icon" | "button_variant" | "is_active" | "show_on_map"> &
    Partial<CountryRow>,
): CountryRow {
  return {
    is_active: true,
    show_on_map: true,
    subtitle: null,
    show_subtitle: false,
    whatsapp_label: "WhatsApp",
    whatsapp_icon: "whatsapp",
    website_label: "Sitio web",
    website_icon: "Globe",
    button_variant: "gold",
    addresses: [],
    created_at: NOW,
    updated_at: NOW,
    ...partial,
  };
}

/** Datos quemados (antes seed Supabase + España del catálogo). */
export const DEFAULT_COUNTRIES: CountryRow[] = [
  country({
    id: "country-co",
    code: "CO",
    name: "Colombia",
    flag: "🇨🇴",
    whatsapp_url: "https://wa.me/573000000000",
    website_url: "https://italuxjoyeria.com/co",
    map_x: 44,
    map_y: 46,
    label_side: "right",
    display_order: 1,
  }),
  country({
    id: "country-ec",
    code: "EC",
    name: "Ecuador",
    flag: "🇪🇨",
    whatsapp_url: "https://wa.me/593000000000",
    website_url: "https://italuxjoyeria.com/ec",
    map_x: 38,
    map_y: 54,
    label_side: "left",
    display_order: 2,
  }),
  country({
    id: "country-cl",
    code: "CL",
    name: "Chile",
    flag: "🇨🇱",
    whatsapp_url: "https://wa.me/56000000000",
    website_url: "https://italuxjoyeria.com/cl",
    map_x: 46,
    map_y: 84,
    label_side: "right",
    display_order: 3,
  }),
  country({
    id: "country-es",
    code: "ES",
    name: "España",
    flag: "🇪🇸",
    whatsapp_url: "https://wa.me/34000000000",
    website_url: "https://italuxjoyeria.com/es",
    map_x: 48,
    map_y: 12,
    label_side: "right",
    display_order: 4,
    show_on_map: false,
  }),
  country({
    id: "country-pe",
    code: "PE",
    name: "Perú",
    flag: "🇵🇪",
    whatsapp_url: "https://wa.me/51000000000",
    website_url: "https://italuxjoyeria.com/pe",
    map_x: 42,
    map_y: 64,
    label_side: "right",
    display_order: 5,
  }),
  country({
    id: "country-mx",
    code: "MX",
    name: "México",
    flag: "🇲🇽",
    whatsapp_url: "https://wa.me/52000000000",
    website_url: "https://italuxjoyeria.com/mx",
    map_x: 22,
    map_y: 18,
    label_side: "left",
    display_order: 6,
  }),
  country({
    id: "country-gt",
    code: "GT",
    name: "Guatemala",
    flag: "🇬🇹",
    whatsapp_url: "https://wa.me/502000000000",
    website_url: "https://italuxjoyeria.com/gt",
    map_x: 28,
    map_y: 28,
    label_side: "left",
    display_order: 7,
  }),
  country({
    id: "country-cr",
    code: "CR",
    name: "Costa Rica",
    flag: "🇨🇷",
    whatsapp_url: "https://wa.me/506000000000",
    website_url: "https://italuxjoyeria.com/cr",
    map_x: 34,
    map_y: 36,
    label_side: "left",
    display_order: 8,
  }),
  country({
    id: "country-do",
    code: "DO",
    name: "República Dominicana",
    flag: "🇩🇴",
    whatsapp_url: "https://wa.me/1809000000",
    website_url: "https://italuxjoyeria.com/do",
    map_x: 52,
    map_y: 28,
    label_side: "right",
    display_order: 9,
  }),
];

export const DEFAULT_FAQS: FaqRow[] = [
  {
    id: "faq-1",
    pregunta: "¿Cuánto tarda en llegar mi pedido?",
    respuesta:
      "Los envíos nacionales llegan entre 2 y 5 días hábiles. Los envíos internacionales se coordinan por WhatsApp con el distribuidor oficial de tu país.",
    activo: true,
    orden: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "faq-2",
    pregunta: "¿Las joyas tienen garantía?",
    respuesta:
      "Sí. Todas nuestras piezas cuentan con garantía de por vida sobre el Oro Laminado 18K Premium contra defectos de fabricación.",
    activo: true,
    orden: 2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "faq-3",
    pregunta: "¿El Oro Laminado 18K pierde el color?",
    respuesta:
      "No. Nuestra capa de Oro Laminado 18K Premium conserva su brillo y color con el cuidado básico recomendado. Evita químicos fuertes y perfumes directos.",
    activo: true,
    orden: 3,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "faq-4",
    pregunta: "¿Puedo comprar por WhatsApp?",
    respuesta:
      "Sí. Cada país cuenta con atención personalizada por WhatsApp con su distribuidor oficial. Selecciona tu país en la sección de países.",
    activo: true,
    orden: 4,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "faq-5",
    pregunta: "¿Realizan envíos seguros?",
    respuesta:
      "Sí. Todos los envíos son asegurados, empacados discretamente y con número de seguimiento desde el momento del despacho.",
    activo: true,
    orden: 5,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "faq-6",
    pregunta: "¿Puedo comprar al por mayor?",
    respuesta:
      'Sí. Contamos con un programa exclusivo para mayoristas y revendedores. Solicita información en la sección "Venta al por mayor".',
    activo: true,
    orden: 6,
    created_at: NOW,
    updated_at: NOW,
  },
];

export const DEFAULT_BENEFITS: BenefitRow[] = [
  {
    id: "benefit-1",
    title: "Garantía de por vida",
    description: "Respaldamos cada pieza para siempre.",
    icon: "ShieldCheck",
    activo: true,
    orden: 1,
    image_url: null,
    image_opacity: 0.2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "benefit-2",
    title: "Oro Laminado 18K Premium",
    description: "Materiales nobles y acabado impecable.",
    icon: "Gem",
    activo: true,
    orden: 2,
    image_url: null,
    image_opacity: 0.2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "benefit-3",
    title: "Diseños exclusivos",
    description: "Colecciones únicas, edición limitada.",
    icon: "Sparkles",
    activo: true,
    orden: 3,
    image_url: null,
    image_opacity: 0.2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "benefit-4",
    title: "Envíos seguros",
    description: "Llegamos a tu puerta con total tranquilidad.",
    icon: "Truck",
    activo: true,
    orden: 4,
    image_url: null,
    image_opacity: 0.2,
    created_at: NOW,
    updated_at: NOW,
  },
];

function sectionText(
  partial: Pick<SectionTextRow, "id" | "section_key"> & Partial<SectionTextRow>,
): SectionTextRow {
  return {
    eyebrow: null,
    title: null,
    subtitle: null,
    show_title: true,
    cta_label: null,
    cta_url: null,
    cta_icon: null,
    bg_image_url: null,
    bg_opacity: null,
    link2_label: null,
    link2_url: null,
    logo_url: null,
    show_logo: true,
    social_instagram: null,
    social_tiktok: null,
    social_facebook: null,
    social_whatsapp: null,
    social_instagram_icon: "Instagram",
    social_tiktok_icon: "tiktok",
    social_facebook_icon: "Facebook",
    social_whatsapp_icon: "whatsapp",
    show_social_instagram: true,
    show_social_tiktok: true,
    show_social_facebook: true,
    show_social_whatsapp: true,
    created_at: NOW,
    updated_at: NOW,
    ...partial,
  };
}

export const DEFAULT_SECTION_TEXTS: SectionTextRow[] = [
  sectionText({
    id: "section-hero",
    section_key: "hero",
    title: "Hero",
    bg_opacity: 30,
  }),
  sectionText({
    id: "section-benefits",
    section_key: "benefits",
    eyebrow: "¿Por qué ITALUX?",
    title: "La promesa de la maison",
  }),
  sectionText({
    id: "section-wholesale",
    section_key: "wholesale",
    eyebrow: "Venta al por Mayor",
    title: "¿Quieres ser distribuidor?",
    subtitle: "Únete a la red oficial ITALUX y lleva la marca a tu ciudad.",
    cta_label: "Contactar un asesor",
    cta_url: SOCIAL_LINKS.whatsapp,
    cta_icon: "whatsapp",
  }),
  sectionText({
    id: "section-footer",
    section_key: "footer",
    title: "ITALUX JOYERÍA",
    eyebrow: "Presencia Internacional",
    social_instagram: SOCIAL_LINKS.instagram,
    social_tiktok: SOCIAL_LINKS.tiktok,
    social_facebook: SOCIAL_LINKS.facebook,
    social_whatsapp: SOCIAL_LINKS.whatsapp,
  }),
];
