export type SectionTextRow = {
  id: string;
  section_key: string;
  eyebrow: string | null;
  title: string | null;
  subtitle: string | null;
  show_title: boolean;
  cta_label: string | null;
  cta_url: string | null;
  cta_icon: string | null;
  bg_image_url: string | null;
  bg_opacity: number | null;
  link2_label: string | null;
  link2_url: string | null;
  logo_url: string | null;
  show_logo: boolean;
  social_instagram: string | null;
  social_tiktok: string | null;
  social_facebook: string | null;
  social_whatsapp: string | null;
  social_instagram_icon: string | null;
  social_tiktok_icon: string | null;
  social_facebook_icon: string | null;
  social_whatsapp_icon: string | null;
  show_social_instagram: boolean;
  show_social_tiktok: boolean;
  show_social_facebook: boolean;
  show_social_whatsapp: boolean;
  created_at: string;
  updated_at: string;
};
