/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ChileCatalogoRouteImport } from './routes/chile.catalogo'
import { Route as AuthenticatedAdminBenefitsRouteImport } from './routes/_authenticated/admin_.benefits'
import { Route as AuthenticatedAdminCatalogsRouteImport } from './routes/_authenticated/admin_.catalogs'
import { Route as AuthenticatedAdminFaqsRouteImport } from './routes/_authenticated/admin_.faqs'
import { Route as AuthenticatedAdminFooterRouteImport } from './routes/_authenticated/admin_.footer'
import { Route as AuthenticatedAdminHeroRouteImport } from './routes/_authenticated/admin_.hero'
import { Route as AuthenticatedAdminWholesaleRouteImport } from './routes/_authenticated/admin_.wholesale'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ChileCatalogoRoute = ChileCatalogoRouteImport.update({
  id: '/chile/catalogo',
  path: '/chile/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminBenefitsRoute =
  AuthenticatedAdminBenefitsRouteImport.update({
    id: '/admin_/benefits',
    path: '/admin/benefits',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCatalogsRoute =
  AuthenticatedAdminCatalogsRouteImport.update({
    id: '/admin_/catalogs',
    path: '/admin/catalogs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFaqsRoute = AuthenticatedAdminFaqsRouteImport.update({
  id: '/admin_/faqs',
  path: '/admin/faqs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminFooterRoute =
  AuthenticatedAdminFooterRouteImport.update({
    id: '/admin_/footer',
    path: '/admin/footer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminHeroRoute = AuthenticatedAdminHeroRouteImport.update({
  id: '/admin_/hero',
  path: '/admin/hero',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminWholesaleRoute =
  AuthenticatedAdminWholesaleRouteImport.update({
    id: '/admin_/wholesale',
    path: '/admin/wholesale',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chile/catalogo': typeof ChileCatalogoRoute
  '/admin/benefits': typeof AuthenticatedAdminBenefitsRoute
  '/admin/catalogs': typeof AuthenticatedAdminCatalogsRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/footer': typeof AuthenticatedAdminFooterRoute
  '/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/admin/wholesale': typeof AuthenticatedAdminWholesaleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chile/catalogo': typeof ChileCatalogoRoute
  '/admin/benefits': typeof AuthenticatedAdminBenefitsRoute
  '/admin/catalogs': typeof AuthenticatedAdminCatalogsRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/footer': typeof AuthenticatedAdminFooterRoute
  '/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/admin/wholesale': typeof AuthenticatedAdminWholesaleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/chile/catalogo': typeof ChileCatalogoRoute
  '/_authenticated/admin_/benefits': typeof AuthenticatedAdminBenefitsRoute
  '/_authenticated/admin_/catalogs': typeof AuthenticatedAdminCatalogsRoute
  '/_authenticated/admin_/faqs': typeof AuthenticatedAdminFaqsRoute
  '/_authenticated/admin_/footer': typeof AuthenticatedAdminFooterRoute
  '/_authenticated/admin_/hero': typeof AuthenticatedAdminHeroRoute
  '/_authenticated/admin_/wholesale': typeof AuthenticatedAdminWholesaleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/chile/catalogo'
    | '/admin/benefits'
    | '/admin/catalogs'
    | '/admin/faqs'
    | '/admin/footer'
    | '/admin/hero'
    | '/admin/wholesale'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/chile/catalogo'
    | '/admin/benefits'
    | '/admin/catalogs'
    | '/admin/faqs'
    | '/admin/footer'
    | '/admin/hero'
    | '/admin/wholesale'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/chile/catalogo'
    | '/_authenticated/admin_/benefits'
    | '/_authenticated/admin_/catalogs'
    | '/_authenticated/admin_/faqs'
    | '/_authenticated/admin_/footer'
    | '/_authenticated/admin_/hero'
    | '/_authenticated/admin_/wholesale'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChileCatalogoRoute: typeof ChileCatalogoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/chile/catalogo': {
      id: '/chile/catalogo'
      path: '/chile/catalogo'
      fullPath: '/chile/catalogo'
      preLoaderRoute: typeof ChileCatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin_/benefits': {
      id: '/_authenticated/admin_/benefits'
      path: '/admin/benefits'
      fullPath: '/admin/benefits'
      preLoaderRoute: typeof AuthenticatedAdminBenefitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/catalogs': {
      id: '/_authenticated/admin_/catalogs'
      path: '/admin/catalogs'
      fullPath: '/admin/catalogs'
      preLoaderRoute: typeof AuthenticatedAdminCatalogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/faqs': {
      id: '/_authenticated/admin_/faqs'
      path: '/admin/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AuthenticatedAdminFaqsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/footer': {
      id: '/_authenticated/admin_/footer'
      path: '/admin/footer'
      fullPath: '/admin/footer'
      preLoaderRoute: typeof AuthenticatedAdminFooterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/hero': {
      id: '/_authenticated/admin_/hero'
      path: '/admin/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AuthenticatedAdminHeroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/wholesale': {
      id: '/_authenticated/admin_/wholesale'
      path: '/admin/wholesale'
      fullPath: '/admin/wholesale'
      preLoaderRoute: typeof AuthenticatedAdminWholesaleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminBenefitsRoute: typeof AuthenticatedAdminBenefitsRoute
  AuthenticatedAdminCatalogsRoute: typeof AuthenticatedAdminCatalogsRoute
  AuthenticatedAdminFaqsRoute: typeof AuthenticatedAdminFaqsRoute
  AuthenticatedAdminFooterRoute: typeof AuthenticatedAdminFooterRoute
  AuthenticatedAdminHeroRoute: typeof AuthenticatedAdminHeroRoute
  AuthenticatedAdminWholesaleRoute: typeof AuthenticatedAdminWholesaleRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminBenefitsRoute: AuthenticatedAdminBenefitsRoute,
  AuthenticatedAdminCatalogsRoute: AuthenticatedAdminCatalogsRoute,
  AuthenticatedAdminFaqsRoute: AuthenticatedAdminFaqsRoute,
  AuthenticatedAdminFooterRoute: AuthenticatedAdminFooterRoute,
  AuthenticatedAdminHeroRoute: AuthenticatedAdminHeroRoute,
  AuthenticatedAdminWholesaleRoute: AuthenticatedAdminWholesaleRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChileCatalogoRoute: ChileCatalogoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
